export const GET_WEATHER_REQUEST = {
    START: 'GET_WEATHER_START',
    SUCCESS: 'GET_WEATHER_SUCCESS',
    FAILURE: 'GET_WEATHER_FAILURE',
};

export const GET_FORECAST_REQUEST = {
    START: 'GET_FORECAST_START',
    SUCCESS: 'GET_FORECAST_SUCCESS',
    FAILURE: 'GET_FORECAST_FAILURE',
};
